language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

script:
  - yarn lint:no-fix
  - yarn test


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
