language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

before_deploy:
  - "yarn docs"

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
